### ISSUE TITLE
goroutine panics

### ISSUE THREAD

**Issue by tomumk** [absolutedevops/civo#3]
Just thought I would create an issue with a few goroutine panic errors I have been having.
No experience with go, so can't help with the actual `fixes`, but thought I could at least highlight some problems to be looked at.

Most commands seem to work great, so its not an invalid setting or something causing these.

```
~/ civo quota
panic: interface conversion: interface is []interface {}, not string

goroutine 1 [running]:
panic(0x749320, 0xc420378640)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/absolutedevops/civo/api.AccountFindByName(0x0, 0x0, 0x605060506050605, 0x507060506050605)
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/api/accounts.go:57 +0x16b
github.com/absolutedevops/civo/cmd.glob..func33(0x955f60, 0x978818, 0x0, 0x0)
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/cmd/quota.go:38 +0x6d
github.com/spf13/cobra.(*Command).execute(0x955f60, 0x978818, 0x0, 0x0, 0x955f60, 0x978818)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:648 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0x9563a0, 0x927ce0, 0xc4200dd1e0, 0x9284e0)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:734 +0x367
github.com/spf13/cobra.(*Command).Execute(0x9563a0, 0xc420101ef0, 0x0)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:693 +0x2b
github.com/absolutedevops/civo/cmd.Execute()
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/cmd/root.go:41 +0x31
main.main()
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/civo.go:47 +0x34
```

```
~/ civo domain records -i [redacted instance ID]
panic: interface conversion: interface is nil, not float64

goroutine 1 [running]:
panic(0x749320, 0xc42036a0c0)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/absolutedevops/civo/cmd.glob..func9(0x952a40, 0xc4200c79e0, 0x0, 0x2)
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/cmd/dns_record.go:55 +0x1fd
github.com/spf13/cobra.(*Command).execute(0x952a40, 0xc4200c78c0, 0x2, 0x2, 0x952a40, 0xc4200c78c0)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:648 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0x9563a0, 0x927ce0, 0xc4200c7360, 0x9284e0)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:734 +0x367
github.com/spf13/cobra.(*Command).Execute(0x9563a0, 0xc4200ebef0, 0x0)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:693 +0x2b
github.com/absolutedevops/civo/cmd.Execute()
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/cmd/root.go:41 +0x31
main.main()
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/civo.go:47 +0x34
```

```
~/ civo domain records --id=[redacted instance ID]
panic: interface conversion: interface is nil, not float64

goroutine 1 [running]:
panic(0x749320, 0xc4202c60c0)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/absolutedevops/civo/cmd.glob..func9(0x952a40, 0xc4200fe1a0, 0x0, 0x1)
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/cmd/dns_record.go:55 +0x1fd
github.com/spf13/cobra.(*Command).execute(0x952a40, 0xc4200fe170, 0x1, 0x1, 0x952a40, 0xc4200fe170)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:648 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0x9563a0, 0x927ce0, 0xc4200c7360, 0x9284e0)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:734 +0x367
github.com/spf13/cobra.(*Command).Execute(0x9563a0, 0xc4200ebef0, 0x0)
	/Users/andy/Code/go/src/github.com/spf13/cobra/command.go:693 +0x2b
github.com/absolutedevops/civo/cmd.Execute()
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/cmd/root.go:41 +0x31
main.main()
	/Users/andy/Code/go/src/github.com/absolutedevops/civo/civo.go:47 +0x34
```

**Comment by tomumk** [comment]
No longer an active customer so closing this. 
Good service, good API, just more expensive than what I already use.
